
spring:
  application:
    name: tradeservice
  zipkin:
    base-url: http://zipkin/
  #sleuth:
  #  sampler:
  #    percentage: 1.0

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/
        